module.exports = {
  TOKEN_ERROR: "Token not correct.",
  NO_TOKEN: "Token required to access API.",
  INVALID_BODY: "Request body is invalid.",
  DATA_SAVED: "Request completed and data saved.",
  DATA_RETRIEVED: "Request completed and data retrieved.",
  DATA_DELETED: "Request completed and data deleted.",
  DATA_UPDATED: "Request completed and data updated.",
  RECORD_NOTFOUND: "Record not found",
  DATA_NOT_FOUND: "Data not found against this query",
  PASSOWRD_MISMATCH: "Old password didn't match",
  PASSOWRD_ERROR: "Password didn't match",
  PASSWORD_UPDATED: "Password has been updated",
  USER_NOTFOUND: "User doesn't exist",
  USER_SIGNEDIN: "User is signed-in",
  USER_LOGGEDOUT: "User is logged-out",
  ADMIN: "ADM",
  SEEDING: "Seeding done successfully",
  SEDDING_FAILURE: "Sedding Failed",
  PASSWORD_EMAIL: "Email sent for password reset.",
  PASSWORD_SET: "User Created and Email sent to set up password.",
  INVALID_COUPON: "Invalid coupon",
  REGISTER_EMAIL: "Email sent for registeration.",
  EMPLOYEE: "Employee",
  DESIGNATION: "Designation",
  RECORD_NOTFOUND: "Record not found",
  EMAIL_EXISTS: "Email already exists",
  EMAIL_SUCCESS: "Email is sent successfully",
  DAILY_EMAIL_SUCCESS: "Daily newsletter is sent successfully",
  Requested_Resource_Not_Found: "Requested Resource Not Found",
};
